### ISSUE TITLE
Updating for Kuro 

### ISSUE THREAD

**Issue by SirSidis** [aymeric-giraudet/hajimari-no-overlay#9]
Would it be possible to modify this to work with the kuro spreadsheet translation? I'd like to build the application for linux to run the overlay on steam deck

**Comment by aymeric-giraudet** [comment]
Hi @SirSidis,

A fork that handles kuro’s translation is here : https://github.com/kiseki-fans/kuro-no-overlay

However if I remember correctly while I was trying to build for Linux, I ran into issues with window transparency on it 🫤
Hope you find a solution !

**Comment by SirSidis** [comment]
Oh that's unfortunate considering that's exactly the issue I was attempting to skirt (https://github.com/doitsujin/dxvk/issues/2358),

Just learned that I can't build for linux on windows unfortunately. Looks like I need to get my old laptop fixed if I want to look into it farther. Thanks for the quick response!
